alias d=docker
alias k=kubectl
alias dc=docker-compose

gp(){ git add -A ;
      git commit -m \"`[[ -z "$1" ]] && echo "Tipo"\" || echo $1`\" ;
      git push ;
      git pull ;
}

bkp (){ cp -a $1 $1-bkp$(date +"%y%m%d%H%M%S") ; }
